---
# vars file for artifacory
artifactory_zip: "https://dl.bintray.com/jfrog/artifactory/jfrog-artifactory-oss-{{ artifactory_version }}.zip"
artifactory_home: "{{ artifactory_download_directory }}/artifactory-oss-{{ artifactory_version }}"
artifactory_user: artifactory
artifactory_group: artifactory
